version: '3'
services:
  jenkins:
    container_name: jenkins
    image: jenkins/jenkins:lts
    volumes:
      - jenkins_home:/var/jenkins_home
    ports:
      - 8080:8080
  express:
    container_name: express
    build: ./express
    ports:
      - "1337:1337"
  client:
    container_name: client
    build: ./client
    ports:
      - "80:3000"
  db:
    container_name: db
    image: postgres
    restart: always
    env_file:
      - pg.env
    ports:
      - "5432:5432"
volumes:
  jenkins_home: {}